import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NextJs Demo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="m-5 text-2xl flex gap-5">
          <Link href={"/"}>Home</Link>
          <Link href={"/performance"}>Performance</Link>
          <Link href={"/reliability"}>Reliability</Link>
          <Link href={"/scale"}>Scale</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
